image: node:latest

before_script:
    - npm install

build:
    stage: build
    script: npm run build:prod
    after_script:
        - cd dist
    artifacts:
        expire_in: 6 week
        paths:
            - LauncherServer.js
