version: '3'
services:
  launcher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1370:1370"
    volumes:
      - data:/app
    # environment:
    #   - AURORA_IS_DEBUG=true
    #   - AURORA_IS_DEV=true

volumes:
  data: 
