// Generated by https://app.quicktype.io/

/**
 * For clients list
 */
export interface VersionManifest {
    versions: Version[];
}

export interface Version {
    id: string;
    type: Type;
    url: string;
}

export enum Type {
    OldAlpha = "old_alpha",
    OldBeta = "old_beta",
    Release = "release",
    Snapshot = "snapshot",
}

export interface Client {
    arguments: Arguments;
    assetIndex: AssetIndex;
    assets: string;
    complianceLevel: number;
    downloads: ClientDownloads;
    id: string;
    javaVersion: JavaVersion;
    libraries: Library[];
    logging: Logging;
    mainClass: string;
    minimumLauncherVersion: number;
    releaseTime: Date;
    time: Date;
    type: string;
}

export interface Arguments {
    game: Array<GameClass | string>;
    jvm: Array<JvmClass | string>;
}

export interface GameClass {
    rules: GameRule[];
    value: string[] | string;
}

export interface GameRule {
    action: Action;
    features: Features;
}

export enum Action {
    Allow = "allow",
}

export interface Features {
    is_demo_user?: boolean;
    has_custom_resolution?: boolean;
}

export interface JvmClass {
    rules: JvmRule[];
    value: string[] | string;
}

export interface JvmRule {
    action: Action;
    os: Purpleos;
}

export interface Purpleos {
    name?: Name;
    version?: string;
    arch?: string;
}

export enum Name {
    Linux = "linux",
    Osx = "osx",
    Windows = "windows",
}

export interface AssetIndex {
    id: string;
    sha1: string;
    size: number;
    totalSize: number;
    url: string;
}

export interface ClientDownloads {
    client: Downloads;
    client_mappings: Downloads;
    server: Downloads;
    server_mappings: Downloads;
}

export interface Downloads {
    sha1: string;
    size: number;
    url: string;
}

export interface JavaVersion {
    component: string;
    majorVersion: number;
}

export interface Library {
    downloads: LibraryDownloads;
    name: string;
    rules?: LibraryRule[];
}

export interface LibraryDownloads {
    artifact: Artifact;
}

export interface Artifact {
    path: string;
    sha1: string;
    size: number;
    url: string;
}

export interface LibraryRule {
    action: Action;
    os: Fluffyos;
}

export interface Fluffyos {
    name: Name;
}

export interface Logging {
    client: LoggingClient;
}

export interface LoggingClient {
    argument: string;
    file: File;
    type: string;
}

export interface File {
    id: string;
    sha1: string;
    size: number;
    url: string;
}

/**
 * For assets
 */
export interface Assets {
    /**
     * Найдено в https://launchermeta.mojang.com/v1/packages/3d8e55480977e32acd9844e545177e69a52f594b/pre-1.6.json \
     * до версии 1.6 (если точнее до снапшота 13w23b)
     */
    map_to_resources?: boolean;
    /**
     * Найдено в https://launchermeta.mojang.com/v1/packages/770572e819335b6c0a053f8378ad88eda189fc14/legacy.json \
     * начиная с версии версии 1.6 (если точнее с снапшота 13w24a) и до 1.7.2 (13w48b)
     */
    virtual?: boolean;
    objects: { [key: string]: Asset };
}

export interface Asset {
    hash: string;
    size: number;
}
