// Generated by https://app.quicktype.io/

/**
 * For clients list
 */
export interface VersionsManifest {
    versions: Version[];
}

export interface Version {
    id: string;
    type: Type;
    url: string;
}

export enum Type {
    OldAlpha = "old_alpha",
    OldBeta = "old_beta",
    Release = "release",
    Snapshot = "snapshot",
}

/**
 * For client
 */
export interface VersionProfile {
    assetIndex: AssetIndex;
    assets: string;
    downloads: VersionProfileDownloads;
    id: string;
    javaVersion: JavaVersion;
    libraries: Library[];
    mainClass: string;
    logging?: Logging;
}

export enum Action {
    Allow = "allow",
    Disallow = "disallow",
}

export enum Name {
    Linux = "linux",
    Osx = "osx",
    Windows = "windows",
}

export interface AssetIndex {
    id: string;
    sha1: string;
    size: number;
    totalSize: number;
    url: string;
}

export interface VersionProfileDownloads {
    client: Client;
}

export interface Client {
    sha1: string;
    size: number;
    url: string;
}

export interface JavaVersion {
    majorVersion: number;
}

export interface Library {
    downloads: LibraryDownloads;
    name: string;
    rules?: LibraryRule[];
    extract?: Extract;
    natives?: Natives;
}

export interface LibraryDownloads {
    artifact?: Artifact;
    classifiers?: Classifiers;
}

export interface Artifact {
    path: string;
    sha1: string;
    size: number;
    url: string;
}

export interface Classifiers {
    "natives-linux"?: Artifact;
    "natives-osx"?: Artifact;
    "natives-windows"?: Artifact;
    "natives-macos"?: Artifact;
    [x: string]: Artifact | undefined;
}

export interface Extract {
    exclude: string[];
}

export type Natives = {
    [x in Name]?: keyof Classifiers;
};

export interface LibraryRule {
    action: Action;
    os?: OS;
}

export interface OS {
    name: Name;
    version?: string;
}

export interface Logging {
    client: LoggingClient;
}

export interface LoggingClient {
    argument: string;
    file: File;
    type: string;
}

export interface File {
    id: string;
    sha1: string;
    size: number;
    url: string;
}
