name: Build

on:
  push:
    branches: [ master, 'feature/gh-workflows' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Download dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Copy result file to main dir
        run: cp dist/LauncherServer.js ./

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: LauncherServer
          path: dist/LauncherServer.js
          if-no-files-found: error
          retention-days: 30