name: Launcher - Testing Build

on:
  push:
    branches: [testing]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_os: "linux"
          - os: windows-latest
            build_os: "win32"
          - os: macos-latest
            build_os: "darwin"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Download dependencies
        run: npm ci

      - name: Build Launcher
        run: npm run build

      - name: Pack Launcher
        run: npm run pack

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Launcher_Testing_${{ matrix.build_os }}
          path: aurora-launcher-${{ matrix.build_os }}-x64
          if-no-files-found: error
          retention-days: 30
