name: Release Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Get version value, set to env
        run: echo "PACKAGE_VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Download dependencies
        run: npm ci

      - name: Build LauncherServer
        run: |
          npm run build:prod
          npm run build:bin

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          name: Aurora LauncherServer ${{ env.PACKAGE_VERSION }}
          files: |
            dist/LauncherServer.js
            dist/LauncherServer_win64.exe
            dist/LauncherServer_linux64
            dist/LauncherServer_mac64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
