name: Testing Build

on:
  push:
    branches: [ testing, 'feature/gh-workflows' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest

    steps:
      - uses: actions/checkout@v2

      - name: Download dependencies
        run: npm install

      - name: Build LauncherServer
        run: npm run build:dev

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: LauncherServer Testing
          path: dist
          if-no-files-found: error
          retention-days: 30